routes/web.php
<?php

///User Routs

Route::group(['namespace' => 'User'],function (){

    Route::get('/', 'HomeController@index');

    Route::get('client/{client}','clientController@client')->name('client');


    Route::get('client/item/{item}','HomeController@item')->name('item');
    Route::get('client/desingation/{desingation}','HomeController@desingation')->name('desingation');

    Route::get('account', 'accountController@index')->name('account');
    Route::get('appoinment', 'appoinmentController@index')->name('appoinment');
});


//Admin Routes

Route::group(['namespace' => 'Admin'],function (){

    Route::get('admin/home', 'HomeController@index')->name('admin.home');
    //User Routes
    Route::resource('admin/user', 'UserController');

//Roles Routes
    Route::resource('admin/role', 'RoleController');

    //Permission Routes
    Route::resource('admin/permission', 'PermissionController');

    //Client Routes
    Route::resource('admin/client', 'ClientController');

    //item Routes
    Route::resource('admin/item', 'itemController');

    //desingation Routes
    Route::resource('admin/desingation', 'desingationController');

    //Account Routes
    Route::resource('admin/account', 'accountController');

    //Cash Routes
    Route::resource('admin/cash', 'cashController');

    //Bankname Routes
    Route::resource('admin/bankname', 'banknameController');

   //Appoinment Routes
    Route::resource('admin/appoinment', 'appoinmentController');

    Route::resource('admin/advertisment', 'advertismentController');

    Route::resource('admin/invoice', 'InvoiceController');

// Admin Auth Routes
    Route::get('admin-login','Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('admin-login','Auth\LoginController@login');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/AccountController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\user\bankname;
use App\Model\user\cash;
use Illuminate\Http\Request;
use App\Model\user\account;
use App\Http\Controllers\Controller;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $accounts   = account::all();
        return view('admin.account.show',compact('accounts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $banknames = bankname::all();
        $cashs = cash::all();
        return view('admin.account.account',compact('banknames','cashs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $this->validate($request,[

            'slug'=>'required',
            'advance'=>'required',
            'dues'=>'required',
            'cheque'=>'required',
            'total'=>'required',

        ]);

        $account = new account;
        $account->slug = $request->slug;
        $account->advance= $request->advance;
        $account->dues = $request->dues;
        $account->cheque = $request->cheque;
        $account->total = $request->total;
        $account->save();
        $account->banknames()->sync($request->bankname);
        $account->cashs()->sync($request->cash);

        return redirect(route('account.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $account = account::with('banknames','cashs')->where('id',$id)->first();
        $banknames = bankname::all();
        $cashs = cash::all();
        return view('admin.account.edit',compact('banknames','cashs','account'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request,[


            'slug'=>'required',
            'advance'=>'required',
            'dues'=>'required',
            'cheque'=>'required',
            'total'=>'required',
        ]);
        $account = account::find($id);
        $account->slug = $request->slug;
        $account->advance= $request->advance;
        $account->dues = $request->dues;
        $account->cheque = $request->cheque;
        $account->total = $request->total;
        $account->banknames()->sync($request->bankname);
        $account->cashs()->sync($request->cash);
        $account->save();

        return redirect(route('account.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        account::where('id',$id)->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/User/AccountController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AccountController extends Controller
{
    public function index()
    {
        return view('user.account');
    }
}

resources/views/admin/account/account.blade.php
@extends('admin.layouts.app')
@section('main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Account Editors
                <small>Advanced form element</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="glyphicon glyphicon-certificate"></i> Home</a></li>
                <li><a href="{{ route('client.index') }}"><i class="glyphicon glyphicon-adjust"></i>Client</a></li>
                <li><a href="{{ route('appoinment.index') }}"><i class="glyphicon glyphicon-adjust"></i>Appoinment</a></li>
                <li><a href="{{ route('advertisment.index') }}"><i class="glyphicon glyphicon-adjust"></i>Advertisment</a></li>
                <li><a href="{{ route('account.index') }}"><i class="glyphicon glyphicon-adjust"></i>Account</a></li>
                <li><a href="{{ route('user.index') }}"><i class="glyphicon glyphicon-adjust"></i>User</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Account Create Form</h3>
                        </div> @include('includes.messages')
                    <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('account.store') }}" method="POST">

                            {{ csrf_field() }}
                            <div class="box-body">

                                <div class=" col-lg-offset-3 col-lg-6">

                                    <div class="form-group">
                                        <label for="slug">Name</label>
                                        <input type="text" class="form-control" id="slug"  name="slug" placeholder="Name">
                                    </div>

                                    <div class="form-group">

                                        <label>Cash:</label>

                                        <div class="row">

                                            @foreach($cashs as $cash)

                                                <div class="col-lg-3">
                                                    <div class="checkbox">
                                                        <label> <input type="checkbox" name="cash[]"  value="{{ $cash->id }}">{{ $cash->name }}</label>
                                                    </div>
                                                </div>
                                            @endforeach

                                        </div>
                                    </div>

                                            <div class="form-group">
                                                <label for="advance">Advance</label>
                                                <input type="text" class="form-control" id="advance"  name="advance" placeholder="Advance">
                                            </div>

                                            <div class="form-group">
                                                <label for="dues">Dues</label>
                                                <input type="text" class="form-control" id="dues"  name="dues" placeholder="Dues">
                                            </div>
                                    <div class="form-group">

                                        <label>Bank Name:</label>

                                        <div class="row">

                                            @foreach($banknames as $bankname)

                                                <div class="col-lg-3">
                                                    <div class="checkbox">
                                                        <label> <input type="checkbox" name="bankname[]"  value="{{ $bankname->id }}">{{ $bankname->name }}|{{ $bankname->brance }}</label>
                                                    </div>
                                                </div>
                                            @endforeach

                                        </div>
                                    </div>
                                            <div class="form-group">
                                                <label for="cheque">Cheque No</label>
                                                <input type="text" class="form-control" id="cheque"  name="cheque" placeholder="Cheque No">
                                            </div>

                                            <div class="form-group">
                                                <label for="total">Total</label>
                                                <input type="text" class="form-control" id="total"  name="total" placeholder="Total">
                                            </div>
                                    <div class="box-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                        <a  href="{{ route('account.index') }}" class="btn btn-warning">Back</a>
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/account/edit.blade.php
@extends('admin.layouts.app')
@section('main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Account Editors
                <small>Advanced form element</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="glyphicon glyphicon-certificate"></i> Home</a></li>
                <li><a href="{{ route('client.index') }}"><i class="glyphicon glyphicon-adjust"></i>Client</a></li>
                <li><a href="{{ route('appoinment.index') }}"><i class="glyphicon glyphicon-adjust"></i>Appoinment</a></li>
                <li><a href="{{ route('advertisment.index') }}"><i class="glyphicon glyphicon-adjust"></i>Advertisment</a></li>
                <li><a href="{{ route('account.index') }}"><i class="glyphicon glyphicon-adjust"></i>Account</a></li>
                <li><a href="{{ route('user.index') }}"><i class="glyphicon glyphicon-adjust"></i>User</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Account Edit Form</h3>
                        @include('includes.messages')
                        <!-- /.box-header -->
                            <!-- form start -->
                            <!-- form start -->
                            <form role="form" action="{{ route('account.update',$account->id) }}" method="POST">

                                {{ csrf_field() }}
                                {{ method_field('PATCH') }}
                            <div class="box-body">

                                <div class="col-lg-6">

                                    <div class="form-group">
                                        <label for="slug">Name</label>
                                        <input type="text" class="form-control" id="slug"  name="slug" placeholder="Organization" value="{{ $account->slug}}">
                                    </div>
                                    <div class="form-group">

                                        <label> Cash</label>
                                        <div class="row">

                                            @foreach($cashs as $cash)

                                                <div class="col-lg-3">
                                                    <div class="checkbox">
                                                        <label> <input type="checkbox" name="cash[]" value="{{ $cash->id }}"
                                                                       @foreach($account->cashs as $account_cash)
                                                                       @if($account_cash->id == $cash->id)
                                                                       checked
                                                                    @endif
                                                                    @endforeach

                                                            >{{ $cash->name }}</label>
                                                    </div>
                                                </div>
                                            @endforeach

                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="advance">Advance</label>
                                        <input type="text" class="form-control" id="advance"  name="advance" placeholder="Advance" value="{{ $account->advance}}">
                                    </div>

                                    <div class="form-group">
                                        <label for="dues">Dues</label>
                                        <input type="text" class="form-control" id="dues"  name="dues" placeholder="Dues" value="{{ $account->dues}}">
                                    </div>
                                    <div class="form-group">

                                        <label> Bank Name</label>
                                        <div class="row">

                                            @foreach($banknames as $bankname)

                                                <div class="col-lg-3">
                                                    <div class="checkbox">
                                                        <label> <input type="checkbox" name="bankname[]" value="{{ $bankname->id }}"
                                                                       @foreach($account->banknames as $account_bankname)
                                                                       @if($account_bankname->id == $bankname->id)
                                                                       checked
                                                                    @endif
                                                                    @endforeach

                                                            >{{ $bankname->name }}</label>
                                                    </div>
                                                </div>
                                            @endforeach

                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="cheque">Cheque No</label>
                                        <input type="text" class="form-control" id="cheque"  name="cheque" placeholder="Cheque No" value="{{ $account->cheque}}">
                                    </div>

                                    <div class="form-group">
                                        <label for="total">Total</label>
                                        <input type="text" class="form-control" id="total"  name="total" placeholder="Total" value="{{ $account->total}}">
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                        <a  href="{{ route('account.index') }}" class="btn btn-warning">Back</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/account/show.blade.php
@extends('admin.layouts.app')
@section('headSection')

    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">

@endsection
@section('main-content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Account
                <small>it all starts here</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="glyphicon glyphicon-certificate"></i> Home</a></li>
                <li><a href="{{ route('client.index') }}"><i class="glyphicon glyphicon-adjust"></i>Client</a></li>
                <li><a href="{{ route('appoinment.index') }}"><i class="glyphicon glyphicon-adjust"></i>Appoinment</a></li>
                <li><a href="{{ route('advertisment.index') }}"><i class="glyphicon glyphicon-adjust"></i>Advertisment</a></li>
                <li><a href="{{ route('account.index') }}"><i class="glyphicon glyphicon-adjust"></i>Account</a></li>
                <li><a href="{{ route('user.index') }}"><i class="glyphicon glyphicon-adjust"></i>User</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">


                    <a class='col-lg-offset-5 btn btn-success' href="{{ route('account.create') }}">Add New</a>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="box">
                        <div class="box-header">
                            @include('includes.messages')
                            <h3 class="box-title">Data Table With Full Features</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>Name</th>
                                    <th>Cash</th>
                                    <th>Bank Name</th>
                                    <th>Brance Name</th>
                                    <th>Cheque No</th>
                                    <th>Advance</th>
                                    <th>Dues</th>
                                    <th>Total</th>
                                    <th>Created At</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($accounts as $account)

                                    <tr>
                                        <td>{{ $loop->index + 1}}</td>
                                        <td>{{ $account->slug }}</td>
                                        <td>
                                            @foreach($account->cashs as $cash)

                                                {{ $cash->name }} |
                                            @endforeach
                                        </td>
                                        <td>
                                            @foreach($account->banknames as $bankname)

                                                {{ $bankname->name }} |
                                            @endforeach
                                        </td>
                                        <td>
                                            @foreach($account->banknames as $bankname)

                                                {{ $bankname->brance }} |
                                            @endforeach
                                        </td>

                                        <td>{{ $account->cheque }}</td>
                                        <td>{{ $account->advance }}</td>
                                        <td>{{ $account->dues }}</td>
                                        <td>{{ $account->advance + $account->dues }}</td>
                                        <td>{{ $account->created_at }}</td>
                                        <td><a href="{{ route('account.edit',$account->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
                                        <td>
                                            <form id="delete-form-{{ $account->id }}" method="POST" action="{{ route('account.destroy',$account->id) }}" style="display: none">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>


                                            <a href="" onclick="
                                                    if(confirm('Are you sure, You went to delete this?'))

                                                    {
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{ $account->id }}').submit();
                                                    }
                                                    else{
                                                    event.preventDefault();
                                                    }
                                                    "><span class="glyphicon glyphicon-trash"></span></a>
                                        </td>

                                    </tr>
                                @endforeach

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>S.No</th>
                                    <th>Name</th>
                                    <th>Cash</th>
                                    <th>Bank Name</th>
                                    <th>Brance Name</th>
                                    <th>Cheque No</th>
                                    <th>Advance</th>
                                    <th>Dues</th>
                                    <th>Total</th>
                                    <th>Created At</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>

                <!-- /.box-footer-->

                <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection
@section('footerSection')
    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $("#example1").DataTable();

        });
    </script>
@endsection